### ISSUE TITLE
Issue with lazy loading and IP Packet Parsing

### ISSUE THREAD

**Issue by ChuckWoodraska** [kisom/pypcapfile#41]
When I try to use lazy loading for the packets and iterate through them the assertion below is hit:
`assert ((magic >> 4) == 4 and (magic & 0x0f) > 4), 'not an IPv4 packet.'`

Here's the traceback:

Traceback (most recent call last):
  File "pcap_speed_test/pcap_test_suite.py", line 55, in <module>
    read_pcap()
  File "pcap_speed_test/pcap_test_suite.py", line 45, in read_pcap
    sss(capfile.packets)
  File "pcap_speed_test/pcap_test_suite.py", line 15, in sss
    print(ip.IP(binascii.unhexlify(ethernet.Ethernet(next_packet.raw()).payload)))
  File "lib/python3.5/site-packages/pcapfile/protocols/network/ip.py", line 34, in __init__
    (magic & 0x0f) > 4), 'not an IPv4 packet.'
AssertionError: not an IPv4 packet.

PCAP file works fine without lazy set. Seems to work fine if I take out the assertion.

**Comment by ChuckWoodraska** [comment]
My bad. Had a try/except that was stopping this on the none lazy load and it is working as expected.

**Comment by kisom** [comment]
@ChuckWoodraska Glad to hear it works!
